version: "3.8"

services:

  tesseract:
    container_name: tesseract
    build: .
    env_file:
      - example.env
    ports:
      - 9095:9095
    volumes:
      - "./data/server:/data"
      - "/Users/renato.durrer/repos/swisstopo/label_studio_data/test_png:/data/test_png"
    environment:
      - LOG_LEVEL=DEBUG

      # Specify the Label Studio URL and API key to access
      # uploaded, local storage and cloud storage files.
      # Do not use 'localhost' as it does not work within Docker containers.
      # Use prefix 'http://' or 'https://' for the URL always.
      # Determine the actual IP using 'ifconfig' (Linux/Mac) or 'ipconfig' (Windows).
      - LABEL_STUDIO_URL=192.168.65.1:8080
      - LABEL_STUDIO_API_KEY=8511dfbe3d6ee012dc456070f8cb7ef216e0f164


  minio:
    container_name: minio
    image: bitnami/minio:latest
    env_file:
      - example.env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ".data/storage:/data"
    command: server /data --console-address ":9001"

